language: node_js
node_js:
  - 6
env:
  global:
    - MONGODB_VERSION=3.4.2
install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
  - mkdir -p data/db
  - mongod --dbpath=data/db &
  - sleep 3
script:
  - mongo --eval 'db.hostInfo()'
  - npm install
  - npm run travis-test
